### ISSUE TITLE
Make GUI Done button more clear

### ISSUE THREAD

**Issue by zachoooo** [ElectricBlocks/electricblocks#36]
Currently when you make any changes to a tile entity, the "Done" button changes its text to "* Done *" to indicate that you need to click it to submit changes. We may want to make that more clear by making it start out saying "Exit" and then when you make a change it could say "Submit Changes". That should make it obvious how the system works to users. The current behavior could be ambiguous.

**Comment by oceanwhit** [comment]
Changed "Done" to "Close", "*Done*" to "Submit Changes"

**Comment by zachoooo** [comment]
Commit 5f476b8 uses hard coded strings for the done button. This should use the internationalization library like was previously done to ensure that non English speakers can still use this program. See https://mcforge.readthedocs.io/en/1.15.x/concepts/internationalization/#netminecraftclientresourcesi18n-client-only

**Comment by zachoooo** [comment]
Fixed in 685e10f
